# Pico setup constants
SIZE_OF_ONE_BUFFER = 1000
NUM_OF_BUFFERS_TO_CAPTURE = 70
CARRIER_FREQ = 6e5
CHANNEL_RANGE = 3

# sending AM signal
TIME_PER_SYMBOL = 0.0001  # seconds
SAMPLES_PER_SIN = 8

BITS_PER_SYMBOL = 2

# Image to chunks constants
CHUNK_SIZE = 2
IMAGE_SIZE = (640, 480)

FIRST_BLOCK = "1010"